# Generated by Django 5.1.4 on 2025-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
