# Generated by Django 5.1.4 on 2025-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
