# Generated by Django 5.1.4 on 2025-01-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_otp_alter_users_email_alter_users_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp',
        ),
    ]
